package model;
// Generated 11-Nov-2023 11:12:48 by Hibernate Tools 4.3.1

import javax.faces.bean.ManagedBean;




/**
 * Students generated by hbm2java
 */

public class Students  implements java.io.Serializable {


     private Integer id;
     private String sname;
     private String email;
     private Integer roll;
     private String image;

    public Students() {
    }

    public Students(String sname, String email, Integer roll, String image) {
       this.sname = sname;
       this.email = email;
       this.roll = roll;
       this.image = image;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getSname() {
        return this.sname;
    }
    
    public void setSname(String sname) {
        this.sname = sname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Integer getRoll() {
        return this.roll;
    }
    
    public void setRoll(Integer roll) {
        this.roll = roll;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }




}


