package model;
// Generated Nov 13, 2023 11:41:47 PM by Hibernate Tools 4.3.1



/**
 * Employees generated by hbm2java
 */
public class Employees  implements java.io.Serializable {


     private Integer id;
     private String ename;
     private String email;
     private String subject;
     private String gender;
     private String locationa;

    public Employees() {
    }

    public Employees(String ename, String email, String subject, String gender, String locationa) {
       this.ename = ename;
       this.email = email;
       this.subject = subject;
       this.gender = gender;
       this.locationa = locationa;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getEname() {
        return this.ename;
    }
    
    public void setEname(String ename) {
        this.ename = ename;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getLocationa() {
        return this.locationa;
    }
    
    public void setLocationa(String locationa) {
        this.locationa = locationa;
    }




}


